// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingJournal.Data;

#nullable disable

namespace TradingJournal.Data.Migrations
{
    [DbContext(typeof(JournalContext))]
    partial class JournalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TradingJournal.Data.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DailyBias")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gedanken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Lots")
                        .HasColumnType("REAL");

                    b.Property<double>("ProfitEuro")
                        .HasColumnType("REAL");

                    b.Property<double>("ProfitProzent")
                        .HasColumnType("REAL");

                    b.Property<double>("RisikoEuro")
                        .HasColumnType("REAL");

                    b.Property<double>("RisikoProzent")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trades", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
